export const AUTH_SETGOOGLEAUTH = 'AUTH_SETGOOGLEAUTH';
export const AUTH_SETPROFILE = 'AUTH_SETPROFILE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const NAVIGATE = 'NAVIGATE';
export const GOBACK = 'GOBACK';

export const IMAGEPROCESS_SET_IMAGEINFO = 'IMAGEPROCESS_SET_IMAGEINFO';